model = "bedrock/amazon.nova-pro-v1:0"
model_turbo = "bedrock/amazon.nova-pro-v1:0"
fallback_models = ["bedrock/amazon.nova-lite-v1:0"]

response_language = "ja-JP" # https://docs.oracle.com/cd/F25597_01/document/products/wli/docs92/xref/xqisocodes.html
