# https://docs.aws.amazon.com/ja_jp/bedrock/latest/userguide/inference-profiles-support.html

[config]
model = "bedrock/apac.anthropic.claude-3-5-sonnet-20240620-v1:0"
# model = "bedrock/amazon.nova-pro-v1:0"
model_turbo = "bedrock/apac.anthropic.claude-3-5-sonnet-20240620-v1:0"
# model_turbo = "bedrock/amazon.nova-pro-v1:0"
fallback_models = ["bedrock/apac.amazon.nova-pro-v1:0"]
# fallback_models = ["bedrock/amazon.nova-lite-v1:0"]

response_language = "ja-JP" # https://docs.oracle.com/cd/F25597_01/document/products/wli/docs92/xref/xqisocodes.html

custom_model_max_tokens = 8000
max_model_tokens = 32000

[github_app]
handle_push_trigger = true
push_trigger_ignore_bot_commits = true
push_trigger_ignore_merge_commits = true
push_trigger_wait_for_initial_review = false
push_trigger_pending_tasks_backlog = false
push_trigger_pending_tasks_ttl = 300
push_commands = [
    "/describe",
    "/review",
]

# https://blog.kinto-technologies.com/posts/2024-06-17-pr-agent/
[pr_reviewer] # /review #
extra_instructions = "/review コマンドの結果は日本語で回答してください"

[pr_description] # /describe #
generate_ai_title = true  # タイトル生成を有効化
title_format = "feat|fix|docs|style|refactor|test|chore({scope}): {description}"  # タイトルのフォーマットを指定

# タイトル生成のための追加指示
extra_instructions = """
タイトルは以下のフォーマットで生成してください：

<format>
- プレフィックス: feat|fix|docs|style|refactor|test|chore
- スコープ: 変更の影響範囲を()で囲む
- 説明: 変更内容を簡潔に記述（日本語可）

例：
- feat(auth): ログイン機能の実装
- fix(api): データ取得時のバリデーションバグを修正
- docs(readme): インストール手順の更新
</format>

/describe コマンドの結果は日本語で回答してください
"""
