[config]
model = "bedrock/apac.amazon.nova-pro-v1:0"
# model = "bedrock/amazon.nova-pro-v1:0"
model_turbo = "bedrock/apac.amazon.nova-pro-v1:0"
# model_turbo = "bedrock/amazon.nova-pro-v1:0"
fallback_models = ["bedrock/apac.amazon.nova-lite-v1:0"]
# fallback_models = ["bedrock/amazon.nova-lite-v1:0"]

response_language = "ja-JP" # https://docs.oracle.com/cd/F25597_01/document/products/wli/docs92/xref/xqisocodes.html

custom_model_max_tokens = 8000
max_model_tokens = 32000

[github_app]
handle_push_trigger = true
push_trigger_ignore_bot_commits = true
push_trigger_ignore_merge_commits = true
push_trigger_wait_for_initial_review = false
push_trigger_pending_tasks_backlog = false
push_trigger_pending_tasks_ttl = 300
push_commands = [
    "/describe",
    "/review",
]

# https://blog.kinto-technologies.com/posts/2024-06-17-pr-agent/
[pr_reviewer] # /review #
extra_instructions = "answer in Japanese"

[pr_description] # /describe #
extra_instructions = "answer in Japanese"
